<a href="https://colab.research.google.com/github/Crisel8a/Probabilidad-1/blob/main/probafundamentosdc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align="center" style="color: #cd7f32;"> Fundamentos de Probabilidad en Python </h1>
@DataCamp



---



# Lanzando una moneda

In [5]:
from scipy.stats import bernoulli

In [6]:
bernoulli.rvs(p=0.5, size=1) #simulando una moneda como un evento bernoulli

array([1])

In [7]:
bernoulli.rvs(p=0.5, size=10) #simulando 10 monedas

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1])

Suponiendo que 1 es cara y 0 es cruz, si queremos saber cuantas caras obtuvimos, entonces hacemos la suma

In [8]:
sum(bernoulli.rvs(p=0.5, size=10))

7

In [27]:
from scipy.stats import binom

In [28]:
binom.rvs(n=10, p=0.5, size=1)

array([8])

In [29]:
binom.rvs(n=10, p=0.5, size=10) #muchos lanzamientos

array([6, 5, 3, 3, 3, 7, 5, 6, 2, 8])





---


# Generando una semilla aleatoria

Usamos el parámetro ``` random_state ``` en la función ``` rvs() ```





In [14]:
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=1, random_state=42)

array([4])

Luego, usamos ``` numpy.random.seed() ``` importando numpy



In [15]:
import numpy as np
np.random.seed(42)

Vamos a lanzar 10 monedas justas con una semilla aleatoria

In [16]:
from scipy.stats import binom
import numpy as np


np.random.seed(42)
binom.rvs(n=10, p=0.5, size=1)

array([4])

---

# Funciones de masa y distribución

Funciones de probabilidad $f(x)=P(X = x)$
- Las funciones de **masa** son para variables aleatorias **discreta**. 
- Las funciones de **densidad** son para variables aleatorias **continuas**. 

La función de distribución $F(x)=P(X \leq x)$


Probability mass function (pmf)
$$binomial.pmf(k,n,p) = {n \choose k}p^k (1-p)^{n-k}$$

En python ``` binom.pmf(k, n, p) ```



In [17]:
#Probabilidad de obtener dos caras luego de 10 lanzamientos de una moneda justa
binom.pmf(k=2, n=10, p=0.5)

0.04394531250000004

In [18]:
# Probabilidad de obtener 5 caras luego de 10 lanzamientos de una moneda justa
binom.pmf(k=5, n=10, p=0.5)

0.24609375000000003

In [19]:
# Probabilidad de obtener 50 caras luego de 100 lanzamientos con probabilidad 0.3
binom.pmf(k=50, n=100, p=0.3)

1.302622713144528e-05

In [20]:
#Probabilidad de obtener 65 caras luego de 100 lanzamientos con probabilidad 0.7
binom.pmf(k=65, n=100, p=0.7)

0.04677968235272997

Probability ditribution function (cdf)

$$binom.cdf(k, n, p) = {n \choose 0}p^0(1-p)^n + {n \choose 1}p(1-p)^{n-1} + \cdots + {n \choose k}p^k(1-p)^{n-k}$$

En python ``` binom.cdf(k, n, p) ```



In [21]:
# Probabilidad de obtener 5 caras o menos en 10 lanzamientos de una moneda justa
binom.cdf(k=5, n=10, p=0.5)

0.623046875

In [22]:
#Probabilidad de obtener 50 caras o menos en 100 lanzamientos con probabilidad 0.3
binom.cdf(k=50, n=100, p=0.3)

0.9999909653138043

Tenemos que $P(X > k) = 1 - P(X \leq k)$, entonces

In [23]:
#Probabilidad de obtener más de 59 caras luego de 100 lanzamientos con probabilidad 0.7
1-binom.cdf(k=59, n=100, p=0.7)

0.9875015928335618

Otra opción es usar ``` .sf ``` luego de `binom`



In [24]:
#Probabilidad de obtener más de 59 caras luego de 100 lanzamientos con probabilidad 0.7
binom.sf(k=59, n=100, p=0.7)

0.9875015928335618



---



# Esperanza, varianza y media aritmética

**Esperanza**: suma de los posibles valores según su probabilidad.
$$E(X)= \sum_{i=1}^k x_ip_i=x_1p_p+x_2p_2+ \cdots + x_kp_k$$

En nuestro caso, para lanzar una moneda obtenermos 
$$E(X)= \sum_{i=1}^2 x_ip_i=x_1p_p+x_2p_2 = 0(1-p) + 1 \cdot p = p$$

**Media Aritmética**: Cada $x_i$ es el resultado de un experiemnto, como lanzar una moneda (puede ser 0 o 1). 

$$ \overline{X} = \frac{1}{n} \sum_{i=1}^n x_i = \frac{1}{n} (x_1+x_2+ \cdots + x_n)$$

En python usamos la función `scipy.stats.describe()` para obtener la media aritmética con `.mean`:

In [25]:
from scipy.stats import describe
describe([0,1]).mean

0.5

**Varianza**: Es una medida de dispersión. Es el valor esperado de la desviasión al cuadrado de ese vlor esperado. 

$$Var(X) = E[(X-E(X))^2]=\sum_{i=1}^n p_i(x_i-E(X))^2$$

En python usamos la función `scipy.stats.describe()` para obtener la media aritmética con `.variance`:

In [26]:
describe([0,1]).variance

0.5



---

# Distribuciones