<a href="https://colab.research.google.com/github/Crisel8a/Probabilidad-1/blob/main/probafundamentosdc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align="center" style="color: #cd7f32;"> Fundamentos de Probabilidad en Python </h1>
@DataCamp



---



# Lanzando una moneda

In [ ]:
from scipy.stats import bernoulli

In [ ]:
bernoulli.rvs(p=0.5, size=1) #simulando una moneda como un evento bernoulli

array([0])

In [ ]:
bernoulli.rvs(p=0.5, size=10) #simulando 10 monedas

array([0, 1, 0, 1, 1, 0, 1, 1, 1, 0])

Suponiendo que 1 es cara y 0 es cruz, si queremos saber cuantas caras obtuvimos, entonces hacemos la suma

In [ ]:
sum(bernoulli.rvs(p=0.5, size=10))

3

In [ ]:
from scipy.stats import binom

In [ ]:
hice cambios

In [ ]:
binom.rvs(n=10, p=0.5, size=1)

array([8])

In [ ]:
binom.rvs(n=10, p=0.5, size=10) #muchos lanzamientos

array([6, 5, 5, 3, 5, 5, 5, 5, 6, 3])





---


# Generando una semilla aleatoria

Usamos el parámetro ``` random_state ``` en la función ``` rvs() ```





In [1]:
from scipy.stats import binom
binom.rvs(n=10, p=0.5, size=1, random_state=42)

array([4])

Luego, usamos ``` numpy.random.seed() ``` importando numpy



In [2]:
import numpy as np
np.random.seed(42)

Vamos a lanzar 10 monedas justas con una semilla aleatoria

In [3]:
from scipy.stats import binom
import numpy as np


np.random.seed(42)
binom.rvs(n=10, p=0.5, size=1)

array([4])

---

# Funciones de masa y distribución

Funciones de probabilidad $f(x)=P(X = x)$
- Las funciones de **masa** son para variables aleatorias **discreta**. 
- Las funciones de **densidad** son para variables aleatorias **continuas**. 

La función de distribución $F(x)=P(X \leq x)$


Probability mass function (pmf)
$$binomial.pmf(k,n,p) = {n \choose k}p^k (1-p)^{n-k}$$

En python ``` binom.pmf(k, n, p) ```



In [4]:
#Probabilidad de obtener dos caras luego de 10 lanzamientos de una moneda justa
binom.pmf(k=2, n=10, p=0.5)

0.04394531250000004

In [5]:
# Probabilidad de obtener 5 caras luego de 10 lanzamientos de una moneda justa
binom.pmf(k=5, n=10, p=0.5)

0.24609375000000003

In [7]:
# Probabilidad de obtener 50 caras luego de 100 lanzamientos con probabilidad 0.3
binom.pmf(k=50, n=100, p=0.3)

1.302622713144528e-05

In [9]:
#Probabilidad de obtener 65 caras luego de 100 lanzamientos con probabilidad 0.7
binom.pmf(k=65, n=100, p=0.7)

0.04677968235272997

Probability ditribution function (cdf)

$$binom.cdf(k, n, p) = {n \choose 0}p^0(1-p)^n + {n \choose 1}p(1-p)^{n-1} + \cdots + {n \choose k}p^k(1-p)^{n-k}$$

En python ``` binom.cdf(k, n, p) ```



In [10]:
# Probabilidad de obtener 5 caras o menos en 10 lanzamientos de una moneda justa
binom.cdf(k=5, n=10, p=0.5)

0.623046875

In [11]:
#Probabilidad de obtener 50 caras o menos en 100 lanzamientos con probabilidad 0.3
binom.cdf(k=50, n=100, p=0.3)

0.9999909653138043

Tenemos que $P(X > k) = 1 - P(X \leq k)$, entonces

In [12]:
#Probabilidad de obtener más de 59 caras luego de 100 lanzamientos con probabilidad 0.7
1-binom.cdf(k=59, n=100, p=0.7)

0.9875015928335618

Otra opción es usar ``` .sf ``` luego de `binom`



In [13]:
#Probabilidad de obtener más de 59 caras luego de 100 lanzamientos con probabilidad 0.7
binom.sf(k=59, n=100, p=0.7)

0.9875015928335618



---

## Esperanza, varianza y promedio

**Esperanza**: suma de los posibles valores según su probabilidad.
$$E(X)= \sum_{i=1}^k x_ip_i=x_1p_p+x_2p_2+ \cdots + x_kp_k$$